services:
  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: my_notes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5434
    networks:
      - webnet
    volumes:
      - postgres-data:/var/lib/postgresql/data  
  
  dataaccess:
    container_name: domain_service
    image: dataaccess:latest
    build:
     context: .
     dockerfile: DataAccess/Dockerfile
    restart: always
    depends_on:
      - postgres
    ports:
      - 9999:8080
    networks:
      - webnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - dataAccessvolume:/var/lib/dataacess/data
      
networks:
  webnet:

volumes: 
  postgres-data:
  dataAccessvolume:
  notesclient:


