services:
  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: my_notes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 54320:5432
    networks:
      - webnet
    volumes:
      - postgres-data:/var/lib/postgresql/data  
  
  dataaccess:
    container_name: domain_service
    image: dataaccess:latest
    build:
     context: .
     dockerfile: DataAccess/Dockerfile
    restart: always
    depends_on:
      - postgres
    ports:
      - 9999:8080
    networks:
      - webnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - dataAccessvolume:/var/lib/dataacess/data

  authservice:
    container_name: auth_service
    image: authenticationservice:latest
    build:
     context: .
     dockerfile: AuthenticationService/Dockerfile
    restart: always
    depends_on:
      - dataaccess
    ports:
      - 8099:8089
    networks:
      - webnet
    environment:
      - ASPNETCORE_HTTP_PORTS=8089
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - authservice:/var/lib/authservice/data


  noteservice:
    container_name: note_service
    image: noteservice:latest
    build:
     context: .
     dockerfile: NoteService/Dockerfile
    restart: always
    depends_on:
      - dataaccess
    ports:
      - 7777:8077
    networks:
      - webnet
    environment:
      - ASPNETCORE_HTTP_PORTS=8077
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - noteservice:/var/lib/noteservice/data

      
networks:
  webnet:

volumes: 
  postgres-data:
  dataAccessvolume:
  notesclient:
  authservice:
  noteservice:



